version: "3.9"

services:
  redis:
    build:
      context: ./redis
      args:
        redis_pw: "${REDIS_PASSWORD:?err}"
    networks:
      - backend
    restart:
      always
    volumes:
      - './redis/dump.rdb:/data/dump.rdb'
    ports:
      - "6379:6379"

  rss_scraper:
    depends_on:
      - redis
    networks:
      - backend
    build:
      context: ./rss_scraper
    restart:
      always
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD:

  web_app:
    build:
      context: ./web_app
    depends_on:
      - redis
      - rss_scraper
    ports:
      - "80:80"
    networks:
      - backend
    restart:
      always
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD:

volumes:
  redis: { }

networks:
  backend:
    driver: bridge