version: "3.9"

services:
  redis:
    build:
      context: ./redis
    networks:
      - backend
    restart:
      always
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    command:
      - /home/user/redis.conf
      - --requirepass ${REDIS_PASSWORD}

  rss_scraper:
    depends_on:
      - redis
    networks:
      - backend
    build:
      context: ./rss_scraper
    restart:
      always
    environment:
      REDIS_HOSTNAME: redis
      REDIS_PASSWORD:

  web_app:
    build:
      context: ./web_app
    depends_on:
      - redis
      - rss_scraper
    ports:
      - "80:5000"
    networks:
      - backend
    restart:
      always
    environment:
      REDIS_HOSTNAME: redis
      REDIS_PASSWORD:

volumes:
  redis: { }

networks:
  backend:
    driver: bridge