name: Deploy Master on AWS with Copilot

# Controls when the workflow will run
on:
#  push:
#    branches:
#      - master
#    paths-ignore:
#      - 'README.md'
#      - '.github/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  copilot:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-2
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Install copilot
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          # download copilot
          curl -Lo copilot-linux https://github.com/aws/copilot-cli/releases/download/v1.8.3/copilot-linux && \
          # make copilot bin executable
          chmod +x copilot-linux && \
          # move to path
          mv copilot-linux $GITHUB_WORKSPACE/bin/copilot && \
          # add to PATH
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: test aws cli credentials
        working-directory: ./copilot
        run: aws iam get-user

      - name: list copilot directory
        working-directory: ./copilot
        run: ls -lha

      - name: copilot help
        working-directory: ./copilot
        run: copilot help

      - name: copilot app init
        working-directory: ./copilot
        run: copilot app init
