name: Dev-Push

# Controls when the workflow will run
on:
  #  push:
  #    branches:
  #      - dev
  #    paths-ignore:
  #      - 'README.md'
  #      - '.github/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows this workflow to be run from another workflow
  workflow_call:

jobs:
  discord_notifcation_dev_push_start:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification - Deploy Successful
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'dev-push workflow started for project {{ EVENT_PAYLOAD.repository.full_name }}.'

  deploy_dev_to_test:
    uses: ./.github/workflows/deploy-dev-to-test.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

  run_lighthouse_on_test:
    needs: [ deploy_dev_to_test ]
    uses: ./.github/workflows/run-lighthouse-on-test.yml

  discord_notifcation_deploy_succcessful:
    needs: [ deploy_dev_to_test, run_lighthouse_on_test ]
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification - Deploy Successful
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed to the TEST environment. It will be live for 10 minutes.'

      - name: Sleep for 10 minutes
        run: sleep 10m
        shell: bash

  undeploy_test_environment:
    needs: [ deploy_dev_to_test, run_lighthouse_on_test, discord_notifcation_deploy_succcessful ]
    if: ${{ always() }}
    uses: ./.github/workflows/undeploy-test-env.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

  discord_notifcation_destroy_done:
    needs: undeploy_test_environment
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification - Destroy Successful
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deleted from the TEST environment after 10 minutes.'

  # TODO: send discord notification on failure