name: Dev-Push

# Controls when the workflow will run
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'README.md'
      - '.github/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows this workflow to be run from another workflow
  workflow_call:

jobs:
  discord_notifcation_dev_push_start:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification - Deploy Successful
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'dev-push workflow started for project {{ EVENT_PAYLOAD.repository.full_name }}.'

  deploy_dev_to_test:
    needs: [ discord_notifcation_dev_push_start ]
    uses: ./.github/workflows/deploy-dev-to-test.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  run_lighthouse_on_test:
    needs: [ deploy_dev_to_test ]
    uses: ./.github/workflows/run-lighthouse-on-test.yml
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  discord_notifcation_deploy_succcessful:
    needs: [ deploy_dev_to_test, run_lighthouse_on_test ]
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification - Waiting
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Leaving TEST-ENV live for 10 minutes'

      - name: Sleep for 10 minutes
        run: sleep 10m
        shell: bash

  undeploy_test_environment:
    needs: [ deploy_dev_to_test, run_lighthouse_on_test, discord_notifcation_deploy_succcessful ]
    if: ${{ always() }}
    uses: ./.github/workflows/undeploy-test-env.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
