name: Run-Lighthouse-on-Test

concurrency: test

# Controls when the workflow will run
on:
# TODO: make run after dev/test deployment
#  push:
#    branches:
#      - dev
#    paths-ignore:
#      - 'README.md'
#      - '.github/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows this workflow to be run from another workflow
  workflow_call:


jobs:
  discord_notifcation_lighthouse_started:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification - lighthouse Started
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'TEST-ENV lighthouse test started on project {{ EVENT_PAYLOAD.repository.full_name }}'

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      # run tests?
      # https://github.com/sdras/awesome-actions
      # https://github.com/marketplace/actions/lighthouse-ci-action

      - name: Lighthouse CI Action
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: 'https://test.911mapr.com/'
          budgetPath: '.github/lighthouse/budget.json'
          configPath: '.github/lighthouse/lighthouserc.json'

      # TODO: send notification to dev

  discord_notifcation_lighthouse_done:
    needs: lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification - Un-deploy Successful
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'TEST-ENV lighthouse test SUCCESSFUL on project {{ EVENT_PAYLOAD.repository.full_name }}'

  discord_notifcation_lighthouse_failed:
    needs: lighthouse
    runs-on: ubuntu-latest
    if: always() && (needs.lighthouse.result == 'failure')
    steps:
      - name: Discord notification - Un-deploy Failed
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'TEST-ENV lighthouse test FAILED on project {{ EVENT_PAYLOAD.repository.full_name }}'
