name: Run-Lighthouse-on-Test

concurrency: test

# Controls when the workflow will run
on:
# TODO: make run after dev/test deployment
#  push:
#    branches:
#      - dev
#    paths-ignore:
#      - 'README.md'
#      - '.github/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      # run tests?
      # https://github.com/sdras/awesome-actions
      # https://github.com/marketplace/actions/lighthouse-ci-action

      - name: Lighthouse CI Action
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: 'https://test.911mapr.com/'
          budgetPath: '.github/lighthouse/budget.json'
          configPath: '.github/lighthouse/lighthouserc-assertions.json'

      # TODO: send notification to dev

